### ISSUE TITLE
Wastevision

### ISSUE THREAD

**Issue by chyuen-devsentient** [devsentient/cdn#18]
![Logo-Header](https://user-images.githubusercontent.com/69875491/219435503-6fa798dd-06b2-4624-adc1-9b1bf7c3deb0.png)

**Comment by albertyu647** [comment]
![wastevision-logo](https://user-images.githubusercontent.com/102254356/171952241-b0b4b2bd-94c9-42a2-80e8-7357579fe29f.svg)

**Comment by albertyu647** [comment]
![wastevision-logo](https://user-images.githubusercontent.com/102254356/171952622-80151050-2c23-407f-8d2a-5b73343cac0c.png)

**Comment by chyuen-devsentient** [comment]
![wastevision-logo-transparent](https://user-images.githubusercontent.com/69875491/219474710-54b9c1fb-9fb7-43e5-a134-7cb39dc1734a.png)
