### ISSUE TITLE
BaptistHealth

### ISSUE THREAD

**Issue by arshia-shakudo** [devsentient/cdn#32]
![BH Logo_color_hor](https://github.com/devsentient/cdn/assets/80602936/b7fe0ca9-bea5-46c0-8b2a-aefccc82a564)
![BH Logo_white_hor](https://github.com/devsentient/cdn/assets/80602936/deb6a4a6-7614-4bdd-8b2f-7c5865b73c6e)

**Comment by arshiamalek** [comment]
![BH Logo_color_stk](https://github.com/devsentient/cdn/assets/80602936/1053136c-e8f8-46a3-ba3d-5e84a3321815)
![BH Logo_Promo_blk_hor](https://github.com/devsentient/cdn/assets/80602936/ad34d2d8-73bf-4c7f-9bbe-5b04e7c85380)

**Comment by arshiamalek** [comment]
![BH Logo_white_stk](https://github.com/devsentient/cdn/assets/80602936/a0235f4d-d027-491a-9342-64f746040113)
