### ISSUE TITLE
StackComponent Logos

### ISSUE THREAD

**Issue by arshia-shakudo** [devsentient/cdn#48]

**Comment by yiran-shakudo** [comment]
Alertmanager 
![image](https://github.com/devsentient/cdn/assets/93139383/ed71d537-93ed-427a-9733-ee7da3191532)

**Comment by yushuo-shakudo** [comment]
Prefect
![prefect-1](https://github.com/devsentient/cdn/assets/170965606/59f5fe23-aedf-49b3-8b18-ba9f885c8a91)

**Comment by yushuo-shakudo** [comment]
Dagster

![dagster-primary-mark](https://github.com/devsentient/cdn/assets/170965606/832a93b0-f3f3-4538-a5a3-ce3a08cbc658)

**Comment by yushuo-shakudo** [comment]
Prefect squared.

![icon128x128](https://github.com/devsentient/cdn/assets/170965606/dde8f02b-f6ec-4713-bab0-c5b0c463964d)

**Comment by yushuo-shakudo** [comment]
vanna
![vanna_ai_logo](https://github.com/devsentient/cdn/assets/170965606/efa8c3a7-453f-4a43-863b-2c4ac44e85e3)

**Comment by arshia-shakudo** [comment]
Langfuse
![icon](https://github.com/devsentient/cdn/assets/80602936/bf304d0a-901a-42ee-b1f2-0cefc0ff4a67)

**Comment by yushuo-shakudo** [comment]
flink
![flink_squirrel_1000](https://github.com/user-attachments/assets/a8684c19-1230-401e-96d5-bb93dfe120c8)

**Comment by asksai-shakudo** [comment]
![290879885-e794ced8-7220-4393-8efc-3faf93bfb503](https://github.com/user-attachments/assets/6d41442b-1602-44f2-9e08-50ee6599b079)

**Comment by asksai-shakudo** [comment]
![image](https://github.com/user-attachments/assets/e8095bfd-1b11-499e-ba03-888d3cfdc91e)

**Comment by yuchen-shakudo** [comment]
<img width="300" alt="logo192" src="https://github.com/user-attachments/assets/b60f4ade-8d0b-4d2e-8892-ecaf77881b6c">

**Comment by yuchen-shakudo** [comment]
![image](https://github.com/user-attachments/assets/ca7f5754-6a1b-4f1e-8aaa-e3ae728e4f25)
![image](https://github.com/user-attachments/assets/71a18244-a0b2-4507-bf3f-5e8fd9e2be6b)

**Comment by yushuo-shakudo** [comment]
langflow
![langflow](https://github.com/user-attachments/assets/3ad540de-5768-4473-b236-0cca94701b0c)

**Comment by yushuo-shakudo** [comment]
Tabby
![6667d9487b1f6-tabbyml-Icon-ezgif com-webp-to-jpg-converter](https://github.com/user-attachments/assets/b14bcbb7-6d49-4e47-96db-3f7d0cf597aa)

**Comment by yushuo-shakudo** [comment]
Taipy
<img width="256" alt="favicon-512x512" src="https://github.com/user-attachments/assets/337c415c-4423-4b42-b03a-ba8e3d5190d9">

**Comment by yuchen-shakudo** [comment]
Neo4j

![image](https://github.com/user-attachments/assets/d4722ded-d678-428a-9dd1-f0a6b00b55e8)

**Comment by yiran-shakudo** [comment]
![image](https://github.com/user-attachments/assets/41d39c6d-770c-420b-9bbe-847398749fed)
pg bouncer

**Comment by yushuo-shakudo** [comment]
![chatnio-logo](https://github.com/user-attachments/assets/83a71dee-dddb-4f01-9fc9-ec33943af06a)
chatnio

**Comment by joowon-shakudo** [comment]
![Image](https://github.com/user-attachments/assets/8728ac88-5e76-4178-bd45-24bfef16a387)
verdaccio
