### ISSUE TITLE
Shakudo logos

### ISSUE THREAD

**Issue by yevgeniy-ds** [devsentient/cdn#6]
![Shakudo-Lockup-RGB-Black](https://user-images.githubusercontent.com/70502043/140454688-f33ba84a-a5dc-42fb-ac47-a256ee61f730.png)
![Shakudo-Lockup-RGB-Copper](https://user-images.githubusercontent.com/70502043/140454691-550d527e-3066-4fb2-b929-ff5d76bc8f18.png)
![Shakudo-Lockup-RGB-White](https://user-images.githubusercontent.com/70502043/140454692-0c02059c-3294-4de0-a6ca-9314ece1d666.png)

**Comment by chyuen-devsentient** [comment]
![symbol-large 7bf8010e](https://user-images.githubusercontent.com/69875491/145663112-52cf5429-123b-4dc5-a14d-0a12ace6f7ff.png)

**Comment by chyuen-devsentient** [comment]
![devsentient](https://user-images.githubusercontent.com/69875491/145663382-8db2799c-9d9b-4e8f-9626-53b3adf1c241.png)

**Comment by yevgeniy-ds** [comment]
![Shakudo-Symbol-RGB-Black](https://user-images.githubusercontent.com/70502043/163713750-8fb57af5-5af6-4e23-8f1c-93dae45c684e.png)
![Shakudo-Symbol-RGB-Copper](https://user-images.githubusercontent.com/70502043/163713751-e1bdd758-23c7-4102-9d3f-e7eda812c5ba.png)
![Shakudo-Symbol-RGB-White](https://user-images.githubusercontent.com/70502043/163713752-9444cc2c-67f7-4d5a-9f3b-126716fd5820.png)
